apiVersion: apps/v1
kind: Deployment
metadata:
  name: express-node-deployment
  labels:
    app: express-node
spec:
  replicas: 1
  selector:
    matchLabels:
      app: express-node
  template:
    metadata:
      labels:
        app: express-node
    spec:
      containers:
      - name: express-node
        image: node
        ports:
        - containerPort: 8080